# 发布空间：ccr.ccs.tencentyun.com/goff/arm-nginx:latest
# 使用 arm64v8/ubuntu:20.04 作为基础镜像
# 占用空间：127 MB
# 使用bash替换ubuntu的dash
# 设置nginx默认使用前台运行 daemon off;
FROM dockerhub.xxx.com/arm64v8/ubuntu:20.04

RUN apt-get update && apt-get install -y tzdata && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone \
&& apt-get install -y wget net-tools telnet inetutils-ping tcpdump tar procps vim zip unzip cron curl apt-utils \
&& wget -P /root/ https://ipc-public-1301730524.cos.ap-guangzhou.myqcloud.com/goff/tsf-consul-template-docker-arm/tsf-consul-template-docker.tar.gz \
&& tar -zxf  /root/tsf-consul-template-docker.tar.gz -C /root/ \
&& mv /root/consul-template /root/tsf-consul-template-docker \
&& rm -rf /root/tsf-consul-template-docker.tar.gz \
&& mkdir -p /data/tsf_std/stdout/logs \
# 安装nodejs和nginx
&& apt install -y gnupg2 ca-certificates lsb-release \
&& mkdir -p /data/nodejs && cd /data/nodejs \
&& wget -c https://nodejs.org/download/release/v12.22.10/node-v12.22.10-linux-arm64.tar.gz && tar -xf node-v12.22.10-linux-arm64.tar.gz \
&& ln -s /data/nodejs/node-v12.22.10-linux-arm64/bin/node /usr/local/bin/node && ln -s /data/nodejs/node-v12.22.10-linux-arm64/bin/npm /usr/local/bin/npm \
&& npm install -g yarn --registry=https://mirrors.tencent.com/npm/ \
&& echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | tee /etc/apt/sources.list.d/nginx.list \
&& curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add - \
&& apt-key fingerprint ABF5BD827BD9BF62 \
&& apt update && apt-cache madison nginx && apt install -y nginx=1.22.0-1~focal && mkdir -p /etc/nginx/logs/ \
&& ln -b -s  /bin/bash  /bin/sh  \
&& sed -i '/worker_processes/adaemon off;' /etc/nginx/nginx.conf

ADD mime.types /etc/nginx/
ADD mime.types /etc/nginx/conf.d/